version: 2

sources:
  - name: dbt-dimensions
    database: dbt
    tables:
      - name: inc_transactions_dimension
      - name: inc_clients_dimension
      - name: inc_employees_dimension
      - name: inc_wallets_dimension
      - name: inc_profiles_dimension
      - name: date_dimension
      - name: time_dimension
      - name: meeza_cost
      - name: txn_proc_cost_table

  - name: dbt-facts
    database: dbt
    tables:
      - name: inc_transactions_fact

  - name: axis_sme
    database: dbt
    tables: 
      - name: bankpaymenttransactions
      - name: bankpayments
      - name: disbursementtransactions